### PR TITLE
Added an @Incomplete annotation that allows acceptance tests to be written early.

### PR DESCRIPTION
**Pull request by ojacobson**
This supports the workflow where an acceptance test is written out before the feature is fully realized; marking the test with `@Incomplete` means that it will no longer cause build failures if tests are run during builds, but will still exercise the feature (unlike JUnit's native `@Ignore`, which skips the test outright).

If the test passes, the test will be _reported_ as a failure, to encourage developers to review features they implement and to keep tests up to date.

### CODE REVIEW

**Comment by ojacobson** [comment]
From @idcmp: "@Incomplete("issue #") ?"

**Comment by lewisd32** [comment]
I like having the option to include a string like that, even if it's not in the message.

**Comment by ajsutton** [comment]
At LMAX we've found tracking an issue number of incomplete tests extremely useful - we even have integration into our ticket system so that if a ticket is closed that still has Incomplete tests an analysis test fails.

**Comment by idcmp** [comment]
Could I convince you that the string is either mandatory, or generates a warning at test time if it's missing? (With an option to fail Incomplete tests lacking a value?)

**Comment by ojacobson** [comment]
I'm inclined to make it mandatory and wait for someone to complain that their team keeps using meaningless messages like `"."`. I actually think it _should_ be optional, but

> @idcmp: 
> Can you tell me the user story behind @Incomplete?
> I ask, as I wonder about attempting to convince you to make a raisin mandatory.

> @ojacobson:
> As a user advocate, I want to be able to write acceptance tests for features that don't exist yet, so that developers can know when they've completed a feature.
> As a developer, I want acceptance tests that are known to cover incomplete features not to break the build, so that I can ship incremental builds and show progress.

> @idcmp:
> So the code is always Incomplete *because* of something being worked on.
> So it's arguable that one would always have something to "point to" as the reason it's incomplete.

is a pretty convincing pro-mandatory argument, and I only have a very weak anti-mandatory counterargument.

**Comment by lewisd32** [comment]
I'll point out that `@Ignore` has an optional freeform value in it, that I always mean to fill in, but sometimes forget.  I more often wish it was required than I am thankful that it's optional.

**Comment by lewisd32** [comment]
lgtm

**Pull request merged**
